workflows:
  test_and_build:
    name: Test and Build Workflow
    environment:
      flutter: stable
      # Additional environment variables can be defined here if needed
    scripts:
      # Step 1: Run Unit and Widget Tests
      - name: Run Unit and Widget Tests
        script: |
          flutter test

      # Step 2: Build Android Debug APK
      - name: Build Android Debug APK
        script: |
          flutter build apk --debug

      # Step 3: Build iOS Debug IPA
      - name: Build iOS Debug IPA
        script: |
          flutter build ios --debug --no-codesign # Add --no-codesign if you don't need to sign the app

    artifacts:
      # Specify the artifacts you want to keep (e.g., APK, IPA, etc.)
      - build/**/outputs/**/*.apk
      - build/ios/iphonesimulator/*.app

    publishing:
      email:
        recipients:
          - muhmmdshabeer@gmail.com  # Replace with your email to receive build notifications

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true